### ISSUE TITLE
Setup CI pipeline to use artifacts to avoid duplicate work

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#2872]
We currently run multiple CI subflows for post-commit to cut down on turn around time:

https://github.com/tenstorrent-metal/tt-metal/blob/main/.github/workflows/all-post-commit-workflows.yaml

```
name: "[post-commit] Run all post-commit workflows"

on:
  workflow_dispatch:

jobs:
  build-and-unit-tests:
    uses: ./.github/workflows/build-and-unit-tests.yaml
    secrets: inherit
  build-and-test-measure-perf:
    uses: ./.github/workflows/perf-models.yaml
    secrets: inherit
  build-and-unit-tests-fast-dispatch:
    uses: ./.github/workflows/fast-dispatch-build-and-unit-tests.yaml
    secrets: inherit
  run-profiler-regression:
    uses: ./.github/workflows/run-profiler-regression.yaml
    secrets: inherit
  run-eager-package-main:
    uses: ./.github/workflows/eager-package-main.yaml
    secrets: inherit
```

However, each step builds TTMetal + fetch python env which is wasteful. Ideally, CI pipeline should build once and re-use artifact/built package for each CI subflow
