### ISSUE TITLE
Investigate pip install error on main branches with torchtrail 0.0.15 after side branch runs which upgrade torchtrail to 0.0.18

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#7063]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8510651249/job/23310229372

is an example pipeline of what we see.

My original hypothesis of not being able to downgrade torchtrail after an upgrade on a branch pipeline might not be correct.

@dimitri-tenstorrent to continue investigating and consider other methods of caching, such as GitHub's.

**Comment by tt-rkim** [comment]
One thing @TT-billteng and I discussed was the need for proper caching of the environment, but also to not install things into the system python.

We should mirror the local virtual environment setup as much as possible in CI. `pipenv` is a candidate and is a supported protocol by `actions/setup-python@v5`.

**Comment by Dimitri-Gnidash** [comment]
When I reproduced the environment as close as I could to the TT-Metal CI install, I was able to upgrade and downgrade the torchtrail library at will without the error `pkg_resources.ContextualVersionConflict: (torchtrail 0.0.17 (/root/python_env/lib/python3.8/site-packages), Requirement.parse('torchtrail==0.0.15'), {'metal-libs'})`
See the screenshot:
![Screenshot 2024-04-02 at 8 26 57 PM](https://github.com/tenstorrent-metal/tt-metal/assets/168645/e68793e3-7c11-4b59-a663-6f637da3d8f0)

**Comment by dimitri-tenstorrent** [comment]
**Quick progress report**
I have found and successfully used the Github action that caches venvs. 
https://github.com/getsentry/action-setup-venv/blob/main/action.yml
```
 - name: "Use Sentry Git Cache"
        uses: getsentry/action-setup-venv@v2.1.0
        id: venv
        with:
          python-version: 3.8
          venv-dir: ./python_env
          cache-dependency-path: |
            tt_metal/python_env/requirements-dev.txt
            pyproject.toml
          install-cmd: make python_env/dev PYTHON_ENV=./python_env -B
```
Successful run: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8545489330/job/23414553425

I have verified that once cached the restoration of cache is about 20 seconds. See this run https://github.com/tenstorrent-metal/tt-metal/actions/runs/8556706887/job/23447185528

Next steps:
 - [ ] push a benign change in requirements in a different branch dimitri/git-cache-change and I want to see the cache invalidated and make sure that the cache in the original branch dimitri/git-change is not invalidated
 - [ ] Think through the current location of venv - ./python_env and I need to confirm that this folder is not shared between the runs as that would mean there is no isolation
 - [ ] Determine which factors should go into the cache key? Is the architecture part of the key? Do we have different grayskull and wormhole envs?
